-- INSERT ROW

INSERT INTO `form_row` (`id`, `id_parent`, `type`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '1', 'p', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-18 14:45:54.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);


-- INSERT COLUMN

INSERT INTO `form_col` (`id`, `id_parent`, `type`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '2', 'i', '2', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-18 14:45:54.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);


INSERT INTO `form_col` (`id`, `id_parent`, `type`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '2', 'i', '2', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-18 14:45:54.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);

-- INSERT COLUMN PROPERTY

INSERT INTO `form_col_property` (`id`, `id_parent`, `property`,`value`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '1', 'label','Imię', '2', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-18 14:45:54.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);


INSERT INTO `form_col_property` (`id`, `id_parent`, `property`,`value`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '2', 'label','Nazwisko', '2', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-18 14:45:54.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);

INSERT INTO `form_col_property` (`id`, `id_parent`, `property`,`value`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '3', 'label','Stanowisko', '2', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-18 14:45:54.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);

INSERT INTO `form_col_property` (`id`, `id_parent`, `property`,`value`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '4', 'label','Pełna nazwa firmy', '2', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-18 14:45:54.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);

-- 21.08.2023

INSERT INTO `form_col_property` (`id`, `id_parent`, `property`, `value`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '5', 'label', '*NIP', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-21 08:01:56.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski87@gmail.com', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);

INSERT INTO `form_col_property` (`id`, `id_parent`, `property`, `value`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '6', 'label', '*Ulica i numer', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-21 08:01:56.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski87@gmail.com', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);

INSERT INTO `form_col_property` (`id`, `id_parent`, `property`, `value`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '7', 'label', '*Kod pocztowy', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-21 08:01:56.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski87@gmail.com', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);

INSERT INTO `form_col_property` (`id`, `id_parent`, `property`, `value`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '8', 'label', '*Miasto', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-21 08:01:56.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski87@gmail.com', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);

INSERT INTO `form_col_property` (`id`, `id_parent`, `property`, `value`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '9', 'label', '*Rok założenia', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-21 08:01:56.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski87@gmail.com', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);

INSERT INTO `form_col_property` (`id`, `id_parent`, `property`, `value`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '10', 'label', '*Liczba pracowników', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-21 08:01:56.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski87@gmail.com', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);

--

INSERT INTO `form_col_property` (`id`, `id_parent`, `property`, `value`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '11', 'label', 'Kapitał zakładowy', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-21 08:01:56.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski87@gmail.com', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);

INSERT INTO `form_col_property` (`id`, `id_parent`, `property`, `value`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '12', 'label', '*Strona WWW', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-21 08:01:56.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski87@gmail.com', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);

INSERT INTO `form_col_property` (`id`, `id_parent`, `property`, `value`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '13', 'label', 'Podmiot powiązany', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-21 08:01:56.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski87@gmail.com', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);

INSERT INTO `form_col_property` (`id`, `id_parent`, `property`, `value`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, '14', 'label', '*Dystrybutorzy w PL', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-21 08:01:56.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski87@gmail.com', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);


-- *Dystrybutorzy w PL ?? Dystrybutorzy powiązani ??


INSERT INTO `form_col` (`id`, `id_parent`, `type`,`order`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, 11, 'i',(SELECT case when max(`fc2`.`order`) is null then 1 else max(`fc2`.`order`)+1 end as `max` FROM `form_col` as `fc2`) ,'2', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-18 14:45:54.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);


INSERT INTO `form_col` (`id`, `id_parent`, `type`,`order`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, (SELECT case when max(`fc1`.`id_parent`) is null then 1 else max(`fc1`.`id_parent`)+1 end as `max` FROM `form_col` as `fc1`), 'i',(SELECT case when max(`fc2`.`order`) is null then 1 else max(`fc2`.`order`)+1 end as `max` FROM `form_col` as `fc2`) ,'2', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-18 14:45:54.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);

INSERT INTO `form_col_property` (`id`, `id_parent`, `property`, `value`, `create_user_id`, `create_user_login`, `create_user_full_name`, `create_user_email`, `create_date`, `create_host`, `mod_user_id`, `mod_user_login`, `mod_user_full_name`, `mod_user_email`, `mod_date`, `mod_host`, `delete_status`, `delete_date`, `delete_reason`) VALUES (NULL, (SELECT case when max(`fc1`.`id_parent`) is null then 1 else max(`fc1`.`id_parent`)+1 end as `max` FROM `form_col_property` as `fc1`), 'label', '-UPDATE-', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski@autos.com.pl', '2023-08-21 08:01:56.000000', '127.0.0.1', '1', 'tborczynski', 'Tomasz Borczyński', 't.borczynski87@gmail.com', CURRENT_TIMESTAMP, '127.0.0.1', '0', NULL, NULL);
