INSERT INTO `slo_font_family` (`NAME`) VALUE ('Helvetica');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Arial');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Arial Black');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Verdana');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Tahoma');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Trebuchet MS');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Impact');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Gill Sans');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Times New Roman');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Georgia');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Palatino');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Baskerville');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Andalé Mono');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Courier');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Lucida');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Monaco');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Bradley Hand');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Brush Script MT');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Luminari');
INSERT INTO `slo_font_family` (`NAME`) VALUE ('Comic Sans MS');