CREATE USER 'forms'@'127.0.0.1' IDENTIFIED VIA mysql_native_password USING '12forms34';

GRANT USAGE ON *.* TO 'forms'@'127.0.0.1' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON `forms`.* TO 'forms'@'127.0.0.1'; ALTER USER 'forms'@'127.0.0.1' ;